[package]
name = "wgpu-bench"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1"
humansize = "2"
pollster = "0.3"
wgpu = "0.17"
